### PR TITLE
add tevents blog post content

### PR DESCRIPTION
**Pull request by rverton**

### CODE REVIEW

**Comment by tylersmalley** [comment]
Thanks @rverton!

Want to pull over the author and avatar files as well from https://github.com/tailscale-dev/tailscale-dev/pull/83/files?

**Comment by rverton** [comment]
It looks like I somehow messed up the git history. As you can see, I have your previous PR commit in my fork: https://github.com/tailscale-dev/tailscale-dev/compare/main...rverton:tailscale-dev:tevents-dev

Maybe you can just merge both PRs? Then author and avatar should also be included.

**Comment by rverton** [comment]
I will add a little additional paragraph today, so you can postpone merging until I have added it if you like.

**Comment by rverton** [comment]
I"m finished so far :)

**Comment by tylersmalley** [comment]
Thanks, @rverton - I see this is a PR into the other branch. So I will merge this and take it from there. 🎉

**Pull request merged**
